In [1]:
import pandas as pd

In [2]:
marks = pd.Series([85, 90, 78, 92]) 
print(marks)

0    85
1    90
2    78
3    92
dtype: int64

In [3]:
city_population = pd.Series({'Delhi': 33800000, 'Mumbai': 20700000, 'Pune': 6800000}) 
print(city_population)

Delhi     33800000
Mumbai    20700000
Pune       6800000
dtype: int64

In [4]:
import numpy as np 
arr = np.array([10, 20, 30]) 
s = pd.Series(arr) 
print(s)

0    10
1    20
2    30
dtype: int32

In [1]:
import pandas as pd

marks = pd.Series(
    [85, 90, 78],
    index=['Math', 'Science', 'English'],
    name='Marks'
)

print(marks)

Math       85
Science    90
English    78
Name: Marks, dtype: int64

In [11]:
data = { 
    'Name': ['Aditi', 'Rohan', 'Meera'], 
    'Age': [21, 23, 22], 
    'City': ['Delhi', 'Mumbai', 'Pune'] 
} 
df = pd.DataFrame(data) 
print(df)

    Name  Age    City
0  Aditi   21   Delhi
1  Rohan   23  Mumbai
2  Meera   22    Pune

In [12]:
rows = [['Aditi', 21], ['Rohan', 23]] 
df = pd.DataFrame(rows, columns=['Name', 'Age']) 
print(df)

    Name  Age
0  Aditi   21
1  Rohan   23

In [13]:
arr = np.array([[1, 2], [3, 4]]) 
df = pd.DataFrame(arr, columns=['A', 'B']) 
print(df)

   A  B
0  1  2
1  3  4

In [14]:
df_csv   = pd.read_csv('students.csv') 
df_excel = pd.read_excel('students.xlsx', sheet_name='Sheet1') 
df_json  = pd.read_json('students.json')

FileNotFoundError: [Errno 2] No such file or directory: 'students.csv'

In [ ]:
df = pd.read_csv('sales.csv') 
df = pd.read_csv('sales.csv', usecols=['Date', 'Revenue'], parse_dates=['Date'])

In [ ]:
df = pd.read_excel('sales.xlsx', sheet_name='Q1') 
# requires: pip install openpyxl

In [ ]:
tables = pd.read_html('https://example.com/stats-page') 
df = tables[0]   # returns a LIST of DataFrames, one per <table> 
# requires: pip install lxml

In [ ]:
df = pd.read_json('sales.json')

In [17]:
df.head(1)

   A  B
0  1  2

In [16]:
df.tail(1)

   A  B
1  3  4

In [18]:
df.sample(1)

   A  B
0  1  2

In [19]:
df.info

<bound method DataFrame.info of    A  B
0  1  2
1  3  4>

In [ ]:
df[df['Age'] > 22] 
df[(df['Age'] > 22) & (df['City'] == 'Pune')]     # AND -> & 
df[(df['City'] == 'Pune') | (df['City'] == 'Delhi')]  # OR -> |

In [ ]:
df[df['City'].isin(['Delhi', 'Pune'])]

In [ ]:
df.query("Age > 22 and City == 'Pune'")

In [ ]:
df.isnull()          # boolean mask, True where missing 
df.isnull().sum()    # count of missing values per column 
df.notnull()