<a href="https://colab.research.google.com/github/abhish3k-397/Python-PEP/blob/main/Day%2018/Day18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day21

In [ ]:
import pandas as pd

In [ ]:
df_csv = pd.read_csv("/content/LPU-Training-Resources/Python/Day_22_23_Pandas/students_clean.csv")

In [ ]:
df_csv.groupby('City')['Math'].mean().round(2)

City
Chennai    60.64
Delhi      73.58
Kolkata    68.00
Mumbai     68.94
Pune       64.96
Name: Math, dtype: float64

In [ ]:
df_csv.groupby('City')['Math'].agg(['count','min','max','mean']).round(2)

         count   min   max   mean
City
Chennai     11  42.0  88.0  60.64
Delhi        8  53.0  95.0  73.58
Kolkata      5  35.0  88.0  68.00
Mumbai       7  37.0  88.0  68.94
Pune         9  41.0  92.0  64.96

In [ ]:
df_csv.groupby('City').agg(
    total_math = ('Math','sum'),
    avg_math = ('Math','mean'),
    students = ('Math','count')
).round(2)

         total_math  avg_math  students
City
Chennai       667.0     60.64        11
Delhi         588.6     73.58         8
Kolkata       340.0     68.00         5
Mumbai        482.6     68.94         7
Pune          584.6     64.96         9

In [ ]:
df_csv.groupby(['City','Gender']).agg(
    total_math = ('Math','sum'),
    avg_math = ('Math','mean'),
    students = ('Math','count'),
    std = ('Math','std')
).round(2)

                total_math  avg_math  students    std
City    Gender
Chennai F            353.0     58.83         6  12.83
        M            314.0     62.80         5  21.46
Delhi   F            268.0     67.00         4  13.78
        M            320.6     80.15         4  12.19
Kolkata F            256.0     64.00         4  24.10
        M             84.0     84.00         1    NaN
Mumbai  F            330.0     66.00         5  24.17
        M            152.6     76.30         2  13.72
Pune    F            286.0     71.50         4  20.17
        M            298.6     59.72         5  13.46

In [ ]:
sales = pd.read_csv("/content/LPU-Training-Resources/Python/Day_22_23_Pandas/sales.csv")

In [ ]:
sales.groupby('Store')['Revenue'].sum().reset_index().sort_values('Revenue',ascending=False)

        Store  Revenue
0   Bengaluru   232850
7        Pune   206450
5      Mumbai   183800
4     Kolkata   171600
1  Chandigarh   171000
3       Delhi   158300
6       Patna   156500
2     Chennai   109200

In [ ]:
orders = pd.read_csv("/content/LPU-Training-Resources/Python/Day_22_23_Pandas/orders.csv")

In [ ]:
customers = pd.read_csv("/content/LPU-Training-Resources/Python/Day_22_23_Pandas/customers.csv")

In [ ]:
jan = orders[orders['OrderDate']<'2026-02-01']
feb = orders[orders['OrderDate']>='2006-02-01']
pd.concat([jan,feb],axis=0,ignore_index=True)

   OrderID  CustID     Product  Amount   OrderDate
0     1001     101      Laptop   55000  2026-01-05
1     1002     102  Headphones    2500  2026-01-08
2     1003     102     Monitor    9800  2026-01-15
3     1001     101      Laptop   55000  2026-01-05
4     1002     102  Headphones    2500  2026-01-08
5     1003     102     Monitor    9800  2026-01-15
6     1004     104    Keyboard    1200  2026-02-02
7     1005     107      Webcam    3200  2026-02-10
8     1006     101       Mouse     700  2026-02-14
9     1007     108      Tablet   21000  2026-03-01

In [ ]:
pd.merge(orders,customers,on='CustID',how='inner')

   OrderID  CustID     Product  Amount   OrderDate          Name     City
0     1001     101      Laptop   55000  2026-01-05    Ananya Rao    Delhi
1     1002     102  Headphones    2500  2026-01-08    Bilal Khan   Mumbai
2     1003     102     Monitor    9800  2026-01-15    Bilal Khan   Mumbai
3     1004     104    Keyboard    1200  2026-02-02  Dev Malhotra  Chennai
4     1006     101       Mouse     700  2026-02-14    Ananya Rao    Delhi

In [ ]:
orders.set_index('CustID').join(customers.set_index('CustID'),how='left')

        OrderID     Product  Amount   OrderDate          Name     City
CustID
101        1001      Laptop   55000  2026-01-05    Ananya Rao    Delhi
102        1002  Headphones    2500  2026-01-08    Bilal Khan   Mumbai
102        1003     Monitor    9800  2026-01-15    Bilal Khan   Mumbai
104        1004    Keyboard    1200  2026-02-02  Dev Malhotra  Chennai
107        1005      Webcam    3200  2026-02-10           NaN      NaN
101        1006       Mouse     700  2026-02-14    Ananya Rao    Delhi
108        1007      Tablet   21000  2026-03-01           NaN      NaN

In [ ]:
print(sales['OrderDate'].dtype)
sales['OrderDate'] = pd.to_datetime(sales['OrderDate'])
print(sales['OrderDate'].dtype)

object
datetime64[ns]

In [ ]:
s_per = pd.read_csv("/content/LPU-Training-Resources/Python/Day_22_23_Pandas/student_performance_project.csv")

In [ ]:
s_per

    StudentID             Name Gender       City  Math  Science  English
0           1     Aditi Sharma      F  Bengaluru  33.0     33.0     74.0
1           2      Rohan Verma      F     Mumbai  78.0     97.0     60.0
2           3       Meera Nair      F      Delhi  90.0     81.0     70.0
3           4      Karan Mehta      F      Delhi  45.0     41.0     70.0
4           5        Sneha Rao      M      Delhi  91.0     80.0     51.0
..        ...              ...    ...        ...   ...      ...      ...
56         57     Qasim Sheikh      M      Delhi  49.0     55.0     91.0
57         58  Reema Chowdhury      F    Kolkata  61.0     47.0     33.0
58         59     Sahil Kapoor      M       Pune  60.0     59.0     34.0
59         60    Tara Krishnan      F    Chennai  79.0      NaN     81.0
60          1     Aditi Sharma      F  Bengaluru  33.0     33.0     74.0

[61 rows x 7 columns]

In [ ]:
s_per.isnull().sum()

StudentID    0
Name         0
Gender       0
City         0
Math         4
Science      3
English      3
dtype: int64

In [ ]:
# s_per.dropna(ignore_index=True)
for col in ['Math', 'Science', 'English']:
    if s_per[col].isnull().any():
        s_per[col] = s_per[col].fillna(s_per[col].mean().round(2))
s_per.isnull().sum()

StudentID    0
Name         0
Gender       0
City         0
Math         0
Science      0
English      0
dtype: int64

In [ ]:
s_per.duplicated().sum()

np.int64(1)

In [ ]:
s_per.drop_duplicates(inplace=True)
# s_per.duplicated().sum()

In [ ]:
s_per.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
58    False
59    False
dtype: bool

In [ ]:
stud_from_del = s_per[s_per['City'] == 'Delhi']
display(stud_from_del.head())

   StudentID          Name Gender   City  Math  Science    English
2          3    Meera Nair      F  Delhi  90.0     81.0  70.000000
3          4   Karan Mehta      F  Delhi  45.0     41.0  70.000000
4          5     Sneha Rao      M  Delhi  91.0     80.0  51.000000
7          8  Vikram Joshi      F  Delhi  48.0     65.0  83.000000
9         10  Rahul Kapoor      F  Delhi  73.0     56.0  63.465517

In [ ]:
display(s_per[['Math','English','Science']].agg(['mean','max']))

           Math    English    Science
mean  62.465497  63.289943  63.114368
max   98.000000  96.000000  98.000000

In [ ]:
total = s_per['Math'] + s_per['Science'] + s_per['English']
s_per['Total'] = total
display(s_per.head())

   StudentID          Name Gender       City  Math  Science  English  Total
0          1  Aditi Sharma      F  Bengaluru  33.0     33.0     74.0  140.0
1          2   Rohan Verma      F     Mumbai  78.0     97.0     60.0  235.0
2          3    Meera Nair      F      Delhi  90.0     81.0     70.0  241.0
3          4   Karan Mehta      F      Delhi  45.0     41.0     70.0  156.0
4          5     Sneha Rao      M      Delhi  91.0     80.0     51.0  222.0

In [ ]:
average = s_per['Total']/3
s_per['Average'] = average
display(s_per.head())

,StudentID,Name,Gender,City,Math,Science,English,Total,Average
0,1,Aditi Sharma,F,Bengaluru,33.0,33.0,74.0,140.0,46.666667
1,2,Rohan Verma,F,Mumbai,78.0,97.0,60.0,235.0,78.333333
2,3,Meera Nair,F,Delhi,90.0,81.0,70.0,241.0,80.333333
3,4,Karan Mehta,F,Delhi,45.0,41.0,70.0,156.0,52.000000
4,5,Sneha Rao,M,Delhi,91.0,80.0,51.0,222.0,74.000000

In [ ]:
rank = s_per['Average'].rank(ascending=False,method='min')
s_per['Rank'] = rank
display(s_per.sort_values('Rank'))

,StudentID,Name,Gender,City,Math,Science,English,Total,Average,Rank
51,52,Lavanya Menon,F,Pune,93.000000,98.00000,96.000000,287.000000,95.666667,1.0
47,48,Hitesh Goyal,F,Pune,91.000000,98.00000,90.000000,279.000000,93.000000,2.0
37,38,Sameer Ansari,F,Chennai,88.000000,82.00000,90.000000,260.000000,86.666667,3.0
2,3,Meera Nair,F,Delhi,90.000000,81.00000,70.000000,241.000000,80.333333,4.0
52,53,Mohit Ahluwalia,F,Chennai,95.000000,80.00000,63.465517,238.465517,79.488506,5.0
1,2,Rohan Verma,F,Mumbai,78.000000,97.00000,60.000000,235.000000,78.333333,6.0
46,47,Gauri Nambiar,F,Mumbai,87.000000,76.00000,64.000000,227.000000,75.666667,7.0
59,60,Tara Krishnan,F,Chennai,79.000000,62.62069,81.000000,222.620690,74.206897,8.0
4,5,Sneha Rao,M,Delhi,91.000000,80.00000,51.000000,222.000000,74.000000,9.0
16,17,Pooja Iyer,M,Chennai,97.000000,60.00000,64.000000,221.000000,73.666667,10.0
18,19,Tanvi Shah,M,Pune,60.000000,86.00000,73.000000,219.000000,73.000000,11.0
45,46,Falak Hussain,M,Kolkata,48.000000,83.00000,87.000000,218.000000,72.666667,12.0
17,18,Siddharth Rana,M,Kolkata,80.000000,39.00000,96.000000,215.000000,71.666667,13.0
29,30,Varun Oberoi,M,Kolkata,79.000000,65.00000,69.000000,213.000000,71.000000,14.0
54,55,Omkar Patil,F,Mumbai,61.000000,62.62069,86.000000,209.620690,69.873563,15.0
26,27,Simran Kaur,M,Mumbai,98.000000,66.00000,45.000000,209.000000,69.666667,16.0
33,34,Harsh Vora,F,Mumbai,57.000000,64.00000,86.000000,207.000000,69.000000,17.0
34,35,Isha Thakur,F,Bengaluru,65.000000,67.00000,72.000000,204.000000,68.000000,18.0
31,32,Rajat Bajaj,M,Chennai,67.000000,49.00000,86.000000,202.000000,67.333333,19.0
55,56,Pallavi Rana,F,Delhi,87.000000,69.00000,46.000000,202.000000,67.333333,19.0
48,49,Ira Vaidya,M,Chennai,58.000000,52.00000,89.000000,199.000000,66.333333,21.0
7,8,Vikram Joshi,F,Delhi,48.000000,65.00000,83.000000,196.000000,65.333333,22.0
56,57,Qasim Sheikh,M,Delhi,49.000000,55.00000,91.000000,195.000000,65.000000,23.0
15,16,Aman Trivedi,F,Pune,57.000000,69.00000,68.000000,194.000000,64.666667,24.0
11,12,Kabir Malik,F,Mumbai,56.000000,85.00000,52.000000,193.000000,64.333333,25.0
23,24,Dev Saxena,M,Mumbai,58.000000,74.00000,61.000000,193.000000,64.333333,25.0
9,10,Rahul Kapoor,F,Delhi,73.000000,56.00000,63.465517,192.465517,64.155172,27.0
10,11,Divya Menon,M,Mumbai,82.000000,45.00000,65.000000,192.000000,64.000000,28.0
13,14,Farhan Sheikh,M,Chennai,47.000000,93.00000,51.000000,191.000000,63.666667,29.0
49,50,Jatin Sood,M,Delhi,48.000000,49.00000,91.000000,188.000000,62.666667,30.0
43,44,Diya Kulkarni,F,Kolkata,61.982456,37.00000,89.000000,187.982456,62.660819,31.0
25,26,Nikhil Bhatia,M,Kolkata,98.000000,47.00000,42.000000,187.000000,62.333333,32.0
27,28,Aryan Reddy,M,Chennai,88.000000,35.00000,63.465517,186.465517,62.155172,33.0
14,15,Neha Chawla,F,Pune,55.000000,62.62069,66.000000,183.620690,61.206897,34.0
53,54,Nisha Sharma,F,Bengaluru,64.000000,72.00000,47.000000,183.000000,61.000000,35.0
6,7,Priya Das,F,Mumbai,61.982456,58.00000,61.000000,180.982456,60.327485,36.0
50,51,Kiran Bhalla,M,Kolkata,48.000000,87.00000,45.000000,180.000000,60.000000,37.0
36,37,Bhavya Chopra,F,Chennai,54.000000,53.00000,71.000000,178.000000,59.333333,38.0
38,39,Nidhi Bansal,F,Mumbai,51.000000,64.00000,63.000000,178.000000,59.333333,38.0
30,31,Ananya Pandey,F,Mumbai,59.000000,54.00000,63.000000,176.000000,58.666667,40.0
8,9,Anjali Gupta,F,Bengaluru,49.000000,77.00000,49.000000,175.000000,58.333333,41.0
42,43,Chirag Rawat,M,Pune,57.000000,66.00000,48.000000,171.000000,57.000000,42.0
32,33,Swati Deshmukh,F,Chennai,36.000000,94.00000,38.000000,168.000000,56.000000,43.0
12,13,Ishita Bose,F,Chennai,45.000000,36.00000,83.000000,164.000000,54.666667,44.0
44,45,Eshan Chatterjee,M,Pune,30.000000,77.00000,57.000000,164.000000,54.666667,44.0
35,36,Kunal Dutta,M,Bengaluru,76.000000,53.00000,30.000000,159.000000,53.000000,46.0
22,23,Sanya Khanna,M,Bengaluru,31.000000,74.00000,52.000000,157.000000,52.333333,47.0
41,42,Bela Shetty,M,Kolkata,32.000000,80.00000,45.000000,157.000000,52.333333,47.0
3,4,Karan Mehta,F,Delhi,45.000000,41.00000,70.000000,156.000000,52.000000,49.0
58,59,Sahil Kapoor,M,Pune,60.000000,59.00000,34.000000,153.000000,51.000000,50.0
24,25,Kavya Pillai,F,Kolkata,46.000000,31.00000,72.000000,149.000000,49.666667,51.0
40,41,Alok Mishra,M,Bengaluru,61.982456,30.00000,56.000000,147.982456,49.327485,52.0
39,40,Om Prakash,M,Kolkata,39.000000,47.00000,59.000000,145.000000,48.333333,53.0
5,6,Arjun Singh,F,Mumbai,35.000000,47.00000,63.000000,145.000000,48.333333,53.0
21,22,Manav Chandra,F,Mumbai,61.982456,51.00000,31.000000,143.982456,47.994152,55.0
57,58,Reema Chowdhury,F,Kolkata,61.000000,47.00000,33.000000,141.000000,47.000000,56.0
28,29,Riya Sinha,F,Pune,64.000000,41.00000,35.000000,140.000000,46.666667,57.0
0,1,Aditi Sharma,F,Bengaluru,33.000000,33.00000,74.000000,140.000000,46.666667,57.0
19,20,Yash Agarwal,F,Bengaluru,47.000000,55.00000,37.000000,139.000000,46.333333,59.0
20,21,Ritu Bhatt,M,Kolkata,30.000000,70.00000,31.000000,131.000000,43.666667,60.0

In [ ]:
s_per['Result'] = s_per[['Math','English','Science']].apply(lambda x: 'Pass' if x.mean() > 50 else 'Fail',axis=1)
display(s_per)

,StudentID,Name,Gender,City,Math,Science,English,Total,Average,Rank,Result
0,1,Aditi Sharma,F,Bengaluru,33.000000,33.00000,74.000000,140.000000,46.666667,57.0,Fail
1,2,Rohan Verma,F,Mumbai,78.000000,97.00000,60.000000,235.000000,78.333333,6.0,Pass
2,3,Meera Nair,F,Delhi,90.000000,81.00000,70.000000,241.000000,80.333333,4.0,Pass
3,4,Karan Mehta,F,Delhi,45.000000,41.00000,70.000000,156.000000,52.000000,49.0,Pass
4,5,Sneha Rao,M,Delhi,91.000000,80.00000,51.000000,222.000000,74.000000,9.0,Pass
5,6,Arjun Singh,F,Mumbai,35.000000,47.00000,63.000000,145.000000,48.333333,53.0,Fail
6,7,Priya Das,F,Mumbai,61.982456,58.00000,61.000000,180.982456,60.327485,36.0,Pass
7,8,Vikram Joshi,F,Delhi,48.000000,65.00000,83.000000,196.000000,65.333333,22.0,Pass
8,9,Anjali Gupta,F,Bengaluru,49.000000,77.00000,49.000000,175.000000,58.333333,41.0,Pass
9,10,Rahul Kapoor,F,Delhi,73.000000,56.00000,63.465517,192.465517,64.155172,27.0,Pass
10,11,Divya Menon,M,Mumbai,82.000000,45.00000,65.000000,192.000000,64.000000,28.0,Pass
11,12,Kabir Malik,F,Mumbai,56.000000,85.00000,52.000000,193.000000,64.333333,25.0,Pass
12,13,Ishita Bose,F,Chennai,45.000000,36.00000,83.000000,164.000000,54.666667,44.0,Pass
13,14,Farhan Sheikh,M,Chennai,47.000000,93.00000,51.000000,191.000000,63.666667,29.0,Pass
14,15,Neha Chawla,F,Pune,55.000000,62.62069,66.000000,183.620690,61.206897,34.0,Pass
15,16,Aman Trivedi,F,Pune,57.000000,69.00000,68.000000,194.000000,64.666667,24.0,Pass
16,17,Pooja Iyer,M,Chennai,97.000000,60.00000,64.000000,221.000000,73.666667,10.0,Pass
17,18,Siddharth Rana,M,Kolkata,80.000000,39.00000,96.000000,215.000000,71.666667,13.0,Pass
18,19,Tanvi Shah,M,Pune,60.000000,86.00000,73.000000,219.000000,73.000000,11.0,Pass
19,20,Yash Agarwal,F,Bengaluru,47.000000,55.00000,37.000000,139.000000,46.333333,59.0,Fail
20,21,Ritu Bhatt,M,Kolkata,30.000000,70.00000,31.000000,131.000000,43.666667,60.0,Fail
21,22,Manav Chandra,F,Mumbai,61.982456,51.00000,31.000000,143.982456,47.994152,55.0,Fail
22,23,Sanya Khanna,M,Bengaluru,31.000000,74.00000,52.000000,157.000000,52.333333,47.0,Pass
23,24,Dev Saxena,M,Mumbai,58.000000,74.00000,61.000000,193.000000,64.333333,25.0,Pass
24,25,Kavya Pillai,F,Kolkata,46.000000,31.00000,72.000000,149.000000,49.666667,51.0,Fail
25,26,Nikhil Bhatia,M,Kolkata,98.000000,47.00000,42.000000,187.000000,62.333333,32.0,Pass
26,27,Simran Kaur,M,Mumbai,98.000000,66.00000,45.000000,209.000000,69.666667,16.0,Pass
27,28,Aryan Reddy,M,Chennai,88.000000,35.00000,63.465517,186.465517,62.155172,33.0,Pass
28,29,Riya Sinha,F,Pune,64.000000,41.00000,35.000000,140.000000,46.666667,57.0,Fail
29,30,Varun Oberoi,M,Kolkata,79.000000,65.00000,69.000000,213.000000,71.000000,14.0,Pass
30,31,Ananya Pandey,F,Mumbai,59.000000,54.00000,63.000000,176.000000,58.666667,40.0,Pass
31,32,Rajat Bajaj,M,Chennai,67.000000,49.00000,86.000000,202.000000,67.333333,19.0,Pass
32,33,Swati Deshmukh,F,Chennai,36.000000,94.00000,38.000000,168.000000,56.000000,43.0,Pass
33,34,Harsh Vora,F,Mumbai,57.000000,64.00000,86.000000,207.000000,69.000000,17.0,Pass
34,35,Isha Thakur,F,Bengaluru,65.000000,67.00000,72.000000,204.000000,68.000000,18.0,Pass
35,36,Kunal Dutta,M,Bengaluru,76.000000,53.00000,30.000000,159.000000,53.000000,46.0,Pass
36,37,Bhavya Chopra,F,Chennai,54.000000,53.00000,71.000000,178.000000,59.333333,38.0,Pass
37,38,Sameer Ansari,F,Chennai,88.000000,82.00000,90.000000,260.000000,86.666667,3.0,Pass
38,39,Nidhi Bansal,F,Mumbai,51.000000,64.00000,63.000000,178.000000,59.333333,38.0,Pass
39,40,Om Prakash,M,Kolkata,39.000000,47.00000,59.000000,145.000000,48.333333,53.0,Fail
40,41,Alok Mishra,M,Bengaluru,61.982456,30.00000,56.000000,147.982456,49.327485,52.0,Fail
41,42,Bela Shetty,M,Kolkata,32.000000,80.00000,45.000000,157.000000,52.333333,47.0,Pass
42,43,Chirag Rawat,M,Pune,57.000000,66.00000,48.000000,171.000000,57.000000,42.0,Pass
43,44,Diya Kulkarni,F,Kolkata,61.982456,37.00000,89.000000,187.982456,62.660819,31.0,Pass
44,45,Eshan Chatterjee,M,Pune,30.000000,77.00000,57.000000,164.000000,54.666667,44.0,Pass
45,46,Falak Hussain,M,Kolkata,48.000000,83.00000,87.000000,218.000000,72.666667,12.0,Pass
46,47,Gauri Nambiar,F,Mumbai,87.000000,76.00000,64.000000,227.000000,75.666667,7.0,Pass
47,48,Hitesh Goyal,F,Pune,91.000000,98.00000,90.000000,279.000000,93.000000,2.0,Pass
48,49,Ira Vaidya,M,Chennai,58.000000,52.00000,89.000000,199.000000,66.333333,21.0,Pass
49,50,Jatin Sood,M,Delhi,48.000000,49.00000,91.000000,188.000000,62.666667,30.0,Pass
50,51,Kiran Bhalla,M,Kolkata,48.000000,87.00000,45.000000,180.000000,60.000000,37.0,Pass
51,52,Lavanya Menon,F,Pune,93.000000,98.00000,96.000000,287.000000,95.666667,1.0,Pass
52,53,Mohit Ahluwalia,F,Chennai,95.000000,80.00000,63.465517,238.465517,79.488506,5.0,Pass
53,54,Nisha Sharma,F,Bengaluru,64.000000,72.00000,47.000000,183.000000,61.000000,35.0,Pass
54,55,Omkar Patil,F,Mumbai,61.000000,62.62069,86.000000,209.620690,69.873563,15.0,Pass
55,56,Pallavi Rana,F,Delhi,87.000000,69.00000,46.000000,202.000000,67.333333,19.0,Pass
56,57,Qasim Sheikh,M,Delhi,49.000000,55.00000,91.000000,195.000000,65.000000,23.0,Pass
57,58,Reema Chowdhury,F,Kolkata,61.000000,47.00000,33.000000,141.000000,47.000000,56.0,Fail
58,59,Sahil Kapoor,M,Pune,60.000000,59.00000,34.000000,153.000000,51.000000,50.0,Pass
59,60,Tara Krishnan,F,Chennai,79.000000,62.62069,81.000000,222.620690,74.206897,8.0,Pass

In [ ]:
gen = s_per.groupby(['Gender'])[['Math','English','Science','Average']].mean()
display(gen)

             Math    English    Science    Average
Gender
F       62.792570  65.174442  63.701826  63.889612
M       62.037787  60.825597  62.346154  61.736512

In [95]:
Topper = s_per.sort_values('Rank').head(10)
display(Topper)

,StudentID,Name,Gender,City,Math,Science,English,Total,Average,Rank,Result
51,52,Lavanya Menon,F,Pune,93.0,98.00000,96.000000,287.000000,95.666667,1.0,Pass
47,48,Hitesh Goyal,F,Pune,91.0,98.00000,90.000000,279.000000,93.000000,2.0,Pass
37,38,Sameer Ansari,F,Chennai,88.0,82.00000,90.000000,260.000000,86.666667,3.0,Pass
2,3,Meera Nair,F,Delhi,90.0,81.00000,70.000000,241.000000,80.333333,4.0,Pass
52,53,Mohit Ahluwalia,F,Chennai,95.0,80.00000,63.465517,238.465517,79.488506,5.0,Pass
1,2,Rohan Verma,F,Mumbai,78.0,97.00000,60.000000,235.000000,78.333333,6.0,Pass
46,47,Gauri Nambiar,F,Mumbai,87.0,76.00000,64.000000,227.000000,75.666667,7.0,Pass
59,60,Tara Krishnan,F,Chennai,79.0,62.62069,81.000000,222.620690,74.206897,8.0,Pass
4,5,Sneha Rao,M,Delhi,91.0,80.00000,51.000000,222.000000,74.000000,9.0,Pass
16,17,Pooja Iyer,M,Chennai,97.0,60.00000,64.000000,221.000000,73.666667,10.0,Pass

In [96]:
s_per.to_csv('student_performance_analysis.csv', index=False)